version: '3.3'
services:
  node:
    image: node:17
    command: bash -c "npm i && npx tsc --watch"
    tty: true
    volumes:
      - .:/app
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    working_dir: /app